### ISSUE TITLE
Hashid as attribute

### ISSUE THREAD

**Issue by ggmm-one** [mtvs/eloquent-hashids#11]
Add the hashid as an attribute to Has Hashid

public function getHashidAttribute()
    {
        return $this->hashid();
    }

**Comment by Yiidiir** [comment]
You can already do `$model->hashid()` what do you mean here?

**Comment by ggmm-one** [comment]
Yes, you can, but that's not very laravel-ish way to do it. On a Laravel Model you use accessors (https://laravel.com/docs/7.x/eloquent-mutators) to get data about the Model. Functions are used more for actions, not to retrieve data. Hope that makes it clear.

**Comment by Yiidiir** [comment]
Agree, this package also lacks encoding/decoding for model properties

**Comment by icaroscherma** [comment]
I agree that it's supposed to be `$model->hashid` but instead of implementing a new function that uses `$model->hashid()` the package should implement itself the `getHashidattribute()` instead of just `hashid()`.

On top of that, instead of using a trait to `HashidRouting` I would preffer enabling the custom key `hashid` on the route model binding, so we could use both `id` and `hashid` as a route-model binder. It's like an optional embedded Custom Resolution Logic. Like the example below:
```PHP
// route sample: http://local/admin/customer/5
Route::get('admin/customer/{customer}', function(App\Customer $customer) {});

// route sample: http://local/customer/E6oNdOxgWoj80qmA
Route::get('customer/{customer:hashid}' function (App\Customer $customer) {});
```

**Comment by icaroscherma** [comment]
I also noticed that this package doesn't follow PSR-2.
Tabulation is being used, not 4 spaces. 👎

**Comment by mtvs** [comment]
This suggestion doesn't feel right to me because we won't be able to use `$model->hashid` as an lvalue - on the left side of an assignment.

**Comment by mtvs** [comment]
@icaroscherma You can already specify a field instead of the default resolution by hashid. I'll add that to the readme.

**Comment by Yiidiir** [comment]
@mtvs what about having hashids in other proprieties rather the ID (mostly hashid refs to other ids)
does it makes sense to have a trait with an array that takes `$hashidAttributes = []` ?

**Comment by icaroscherma** [comment]
@Yiidiir 

> what about having hashids in other proprieties rather the ID (mostly hashid refs to other ids)
> does it makes sense to hav

You mean use something like:
```PHP
// Post.php
protected $hashidAttributes = [
    'id',
    'user_id',
];
```
To be able to automatically use a query scope for hashids?

But why would you need that for? If you're just reflecting the foreign-key to use in like a route, you can just use the route binding, like:

```PHP
Route::get('users/{user:hashid}/post/{post:hashid}', function(App\User $user, App\Post $post) {});
```

And if you need to use for query-relations, you can use something like:
```PHP
App\Post::whereHas('user', function ($q) {
    return $q->whereHashid('E6oNdOxgWoj80qmA');
})->get();
```

---

@mtvs 

> This suggestion doesn't feel right to me because we won't be able to use $model->hashid as an lvalue - on the left side of an assignment.

I don't understand what you mean.

> @icaroscherma You can already specify a field instead of the default resolution by hashid. I'll add that to the readme.

I know, but what I mean is that I want to be able to use the `hashid` as an OPTION, not changing the default route key to it.
If I use your library, I will need to use `{model:id}` for every route of every single Model that uses your Trait. So if I have public routes with a hashed id and admin routes with the main `id`, the `id` will need to be explicit, not otherwise as I suggested.

**Comment by Yiidiir** [comment]
@icaroscherma 
No I meant manipulating data in the controller, for example you have a hashid as body input that is a reference to another model and you use a pivot table or a one-to-many relationship,
The best approach I can think of are mutilators so I was thinking having an universal mutator that checks for existence of hashid-ed values and hash them can be helpful?

**Comment by icaroscherma** [comment]
@Yiidiir 

I understand your approach to use mutators, but I don't recommend storing hashids, they're supposed to be "virtual fields" (non-persisted). You should hash an id only to public display it.

So if in your view you have a input field pointing to a FK using hashids, you can use the exact example I showed you before. Instead of searching for `user_id` you search for `whereHas` and then point to the relationship that has the hashid trait.

> Also using closures for the routes has downfalls like not being able to cache them

Of course, but my example was just for easy understanding, you can replace the closure (2nd argument) for a Controller and function without changing anything I said.


Ahhh, about the "universal" decoder, it's just one Facade away ;) `Hashid::decode($whatYouNeedToDecode);`.

**Comment by Yiidiir** [comment]
@icaroscherma I don't store hashids at all but I use the hashids for the frontend and i get them as input refs to different models and that's why I need something to decode them automatically 
```    
public function store(Request $request)
    {
        $post = Post::create($request->only(['title', 'body', 'topic_id']); // Well can't do this unless I have a mutatator for topicIdAttrobute!
       ...
}
```
Instead I have to do this which sucks
```    
public function store(Request $request)
    {
        $post = Post::create([
        ...
        'topic_id' => Hashid::decode($request->topic_id)
        ...
         ]);
       ...
}
```
I know there are many ways to fix this like altering the value at request level but I find it confusing to not be able to have the dehashing/hashing easily for other attributes like primary key, I might be wrong, please correct me

**Comment by icaroscherma** [comment]
@Yiidiir I see your point now. I preffer to handle it on request level so I have the responsibilities pretty well defined but you can fork this package and implement like:

```PHP
// app/Post.php
protected $casts = [
    'user_id' => App\Casts\MayHashid::class,
];

// app/Casts/MayHashid.php
namespace App\Casts;
use Illuminate\Contracts\Database\Eloquent\CastsAttributes;
use Vinkla\Hashids\Facades\Hashids;
class MayHashid implements CastsAttributes
{
    // I'm not sure if the `get` function it's mandatory or not.
    public function get($model, $key, $value, $attributes)
    {
        return $value; // If you want always it to be hashed, comment this line
        return Hashid::encode($value);
    }
    public function set($model, $key, $value, $attributes)
    {
        return Hashid::decode($value)[0] ?? $value;
    }
}
```

**Comment by Yiidiir** [comment]
@icaroscherma Thats what I meant, I thought having a trait that uses a protected model property can be faster, can you think of any downfalls of something like :
```
Trait HasHashidAttributes
public function getAttribute($key)
{
     if (in_array($key, $this->hashidAttributes ) {
     // return decoded hashid
     }
    ...
```
and then 
```
// Post.php
...
use HasHashidAttributes;
```

**Comment by ggmm-one** [comment]
Well, I started my own repo to better cater to my needs. Maybe it will for your needs too: https://github.com/ggmm-one/eloquent-hashids
